package com.brandempiricism.etocrm.platform.tenancy;

import static org.assertj.core.api.Assertions.assertThat;
import static org.hamcrest.Matchers.hasItem;
import static org.mockito.Mockito.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

import com.fasterxml.jackson.databind.JsonNode;import com.fasterxml.jackson.databind.ObjectMapper;import org.junit.jupiter.api.Test;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.beans.factory.annotation.Qualifier;import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.http.MediaType;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.test.context.bean.override.mockito.MockitoBean;import org.springframework.test.web.servlet.*;

@SpringBootTest @AutoConfigureMockMvc
class TenantProvisioningTest{
 @Autowired MockMvc mvc;@Autowired ObjectMapper json;@Autowired @Qualifier("platformJdbcTemplate") JdbcTemplate jdbc;@Autowired @Qualifier("tenantJdbcTemplate") JdbcTemplate tenantJdbc;
 @MockitoBean TenantProvisioningInfrastructure infrastructure;
 @MockitoBean TenantAdministratorProvisioner administrators;
 @Test void initialClientIsRegisteredForDedicatedDatabaseProvisioning()throws Exception{mvc.perform(get("/api/platform/tenants")).andExpect(status().isOk()).andExpect(jsonPath("$[?(@.slug == 'r-hyper-tooling')].displayName").value(hasItem("R Hyper Tooling"))).andExpect(jsonPath("$[?(@.slug == 'r-hyper-tooling')].website").value(hasItem("https://rhypertooling.ca/"))).andExpect(jsonPath("$[?(@.slug == 'r-hyper-tooling')].databaseName").value(hasItem("eto_crm_r_hyper_tooling"))).andExpect(jsonPath("$[?(@.slug == 'r-hyper-tooling')].provisioningStep").value(hasItem("REGISTERED")));}
 @Test void repeatedProvisioningKeyReturnsSameTenantWithoutDuplication()throws Exception{String request="""
 {"slug":"example-tools","displayName":"Example Tools","website":"https://example.com/","idempotencyKey":"provision-example-tools"}
 """;JsonNode first=body(mvc.perform(post("/api/platform/tenants").header("X-Actor","platform-operator").header("X-Request-Id","provision-request-1").contentType(MediaType.APPLICATION_JSON).content(request)).andExpect(status().isAccepted()).andExpect(header().string("X-Request-Id","provision-request-1")).andReturn());JsonNode second=body(mvc.perform(post("/api/platform/tenants").header("X-Actor","platform-operator").contentType(MediaType.APPLICATION_JSON).content(request)).andExpect(status().isAccepted()).andReturn());assertThat(second.get("id").asText()).isEqualTo(first.get("id").asText());assertThat(jdbc.queryForObject("select count(*) from tenant_registry where idempotency_key='provision-example-tools'",Integer.class)).isEqualTo(1);}
 @Test void invalidCorrelationInputIsNotReflectedAndProblemIncludesRequestId()throws Exception{MvcResult result=mvc.perform(post("/api/platform/tenants").header("X-Actor","platform-operator").header("X-Request-Id","bad value").contentType(MediaType.APPLICATION_JSON).content("{}" )).andExpect(status().isUnprocessableEntity()).andExpect(jsonPath("$.requestId").isNotEmpty()).andReturn();assertThat(result.getResponse().getHeader("X-Request-Id")).doesNotContain(" ").isEqualTo(json.readTree(result.getResponse().getContentAsString()).get("requestId").asText());}
 @Test void platformAndTenantSchemasArePhysicallySeparated(){assertThat(tableCount(jdbc,"TENANT_REGISTRY")).isEqualTo(1);assertThat(tableCount(jdbc,"ACCOUNT")).isZero();assertThat(tableCount(tenantJdbc,"ACCOUNT")).isEqualTo(1);assertThat(tableCount(tenantJdbc,"TENANT_REGISTRY")).isZero();}
 @Test void activatesOnlyAfterEveryProvisioningStepCompletes()throws Exception{String request="""
 {"slug":"workflow-tools","displayName":"Workflow Tools","website":"https://example.com/","idempotencyKey":"provision-workflow-tools"}
 """;JsonNode registered=body(mvc.perform(post("/api/platform/tenants").header("X-Actor","platform-operator").contentType(MediaType.APPLICATION_JSON).content(request)).andExpect(status().isAccepted()).andReturn());var id=java.util.UUID.fromString(registered.get("id").asText());var spec=new TenantProvisioningInfrastructure.TenantDatabaseSpec(id,"workflow-tools","eto_crm_workflow_tools");when(infrastructure.allocateDatabase(spec)).thenReturn(new TenantProvisioningInfrastructure.Allocation("secret://tenants/workflow-tools/database"));mvc.perform(post("/api/platform/tenants/{id}/provision",id).header("X-Actor","platform-operator")).andExpect(status().isAccepted()).andExpect(jsonPath("$.status").value("ACTIVE")).andExpect(jsonPath("$.provisioningStep").value("COMPLETE"));var order=inOrder(infrastructure,administrators);order.verify(infrastructure).allocateDatabase(spec);order.verify(infrastructure).migrate(spec,"secret://tenants/workflow-tools/database");order.verify(infrastructure).seedDefaults(spec,"secret://tenants/workflow-tools/database");order.verify(infrastructure).verify(spec,"secret://tenants/workflow-tools/database");order.verify(administrators).assignInitialAdministrator(id,"platform-operator");}
 private JsonNode body(MvcResult result)throws Exception{return json.readTree(result.getResponse().getContentAsString());}
 private static int tableCount(JdbcTemplate database,String table){return database.queryForObject("select count(*) from information_schema.tables where table_schema='PUBLIC' and table_name=?",Integer.class,table);}
}
