package com.brandempiricism.etocrm.prospecting.match;
import com.brandempiricism.etocrm.accounts.*;import com.brandempiricism.etocrm.capabilities.*;import com.brandempiricism.etocrm.prospecting.*;import com.brandempiricism.etocrm.prospecting.signal.SignalService;import java.time.*;import java.util.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service public class MatchService implements ProspectingApplicationApi{
 private final AccountApplicationApi accounts;private final CapabilityApplicationApi capabilities;private final SignalService signals;private final MatchRepository matches;
 MatchService(AccountApplicationApi accounts,CapabilityApplicationApi capabilities,SignalService signals,MatchRepository matches){this.accounts=accounts;this.capabilities=capabilities;this.signals=signals;this.matches=matches;}
 @Transactional public MatchView createForAccount(UUID accountId,CreateAccountMatch request,String actor){var account=accounts.getAccount(accountId);var signal=signals.get(accountId,request.signalId());var missing=missing("recorded",LocalDate.now(),"recorded",request.owner(),request.hypothesis(),request.nextAction(),request.nextActionDate());return save(account,signal.id(),request.capabilityId(),request.owner(),request.hypothesis(),request.nextAction(),request.nextActionDate(),missing,actor);}
 @Transactional public MatchView createWalkingSlice(CreateWalkingSlice request,String actor){var missing=missing(request.source(),request.observedOn(),request.observedFact(),request.owner(),request.hypothesis(),request.nextAction(),request.nextActionDate());var account=accounts.createAccount(new AccountApplicationApi.CreateAccount(request.accountName(),request.industry(),request.location(),request.website(),null,null,request.contacts()==null?List.of():request.contacts().stream().map(c->new AccountApplicationApi.CreateContact(c.name(),c.email(),c.role(),c.notes())).toList()),actor);var signal=signals.create(account.id(),new SignalService.CreateSignal(request.source(),request.observedOn(),request.observedFact(),request.assumption()),actor,true);return save(account,signal.id(),request.capabilityId(),request.owner(),request.hypothesis(),request.nextAction(),request.nextActionDate(),missing,actor);}
 private MatchView save(AccountApplicationApi.AccountRef account,UUID signalId,UUID capabilityId,String owner,String hypothesis,String nextAction,LocalDate nextActionDate,List<String> missing,String actor){var capability=capabilities.get(capabilityId);if(!capability.active()&&missing.isEmpty())throw new IllegalArgumentException("Select an active capability before activating this match.");var status=missing.isEmpty()?MatchStatus.ACTIVE:MatchStatus.DRAFT;var entity=new MatchEntity(UUID.randomUUID(),account.id(),signalId,capability.id(),account.name(),capability.name(),clean(owner),clean(hypothesis),clean(nextAction),nextActionDate,status,Instant.now(),actor);matches.save(entity);return view(entity,missing);}
 List<MatchView> list(UUID accountId){accounts.getAccount(accountId);return matches.findByAccountIdOrderByCreatedAtDesc(accountId).stream().map(m->view(m,List.of())).toList();}
 MatchView get(UUID accountId,UUID id){accounts.getAccount(accountId);var match=find(id);if(!match.accountId.equals(accountId))throw new IllegalArgumentException("Capability match does not belong to this account.");return view(match,List.of());}
 public List<RelatedMatch> listForSignal(UUID accountId,UUID signalId){return matches.findByAccountIdAndSignalIdOrderByCreatedAtDesc(accountId,signalId).stream().map(m->new RelatedMatch(m.id,m.capabilityName,m.status.name(),m.hypothesis)).toList();}
 List<MatchView> queue(String owner){return matches.findByOwnerAndStatusOrderByNextActionDateAsc(owner,MatchStatus.ACTIVE).stream().map(m->view(m,List.of())).toList();}
 @Override public MatchRef getMatch(UUID id){var m=find(id);return new MatchRef(m.id,m.accountId,m.accountName,m.capabilityName,m.status.name());}
 private MatchEntity find(UUID id){return matches.findById(id).orElseThrow(()->new IllegalArgumentException("Capability match does not exist."));}
 private static List<String> missing(String source,LocalDate observedOn,String fact,String owner,String hypothesis,String action,LocalDate due){var result=new ArrayList<String>();if(blank(source))result.add("Add the signal source.");if(observedOn==null)result.add("Add the observation date.");if(blank(fact))result.add("Describe the observed fact separately from assumptions.");if(blank(owner))result.add("Assign an owner.");if(blank(hypothesis))result.add("Explain why the capability fits the observed need.");if(blank(action))result.add("Describe the next action.");if(due==null)result.add("Set the next-action date.");return List.copyOf(result);}
 private static MatchView view(MatchEntity m,List<String> missing){return new MatchView(m.id,m.accountId,m.signalId,m.capabilityId,m.status.name(),m.accountName,m.capabilityName,m.owner,m.hypothesis,m.nextAction,m.nextActionDate,missing,m.createdAt);}
 private static boolean blank(String v){return v==null||v.isBlank();}private static String clean(String v){return blank(v)?null:v.trim();}
 public record CreateAccountMatch(UUID signalId,UUID capabilityId,String owner,String hypothesis,String nextAction,LocalDate nextActionDate){}
 public record CreateWalkingSlice(String accountName,String industry,String location,String website,UUID capabilityId,String source,LocalDate observedOn,String observedFact,String assumption,String owner,String hypothesis,String nextAction,LocalDate nextActionDate,List<ContactInput> contacts){}
 public record ContactInput(String name,String email,String role,String notes){}
 public record MatchView(UUID id,UUID accountId,UUID signalId,UUID capabilityId,String status,String accountName,String capabilityName,String owner,String hypothesis,String nextAction,LocalDate nextActionDate,List<String> missingInformation,Instant createdAt){}
 public record RelatedMatch(UUID id,String capabilityName,String status,String hypothesis){}
}
