import { FormEvent, useState } from 'react'
import type { Capability, ContactInput, CreateMatchInput } from './prospectCapabilityMatchTypes'

type Props={capabilities:Capability[]; owner:string; saving:boolean; onOwnerChange:(owner:string)=>void; onSubmit:(input:CreateMatchInput)=>void}
const emptyContact=():ContactInput=>({name:'',email:'',role:'',notes:''})
const required=<span className="required" aria-label="required">*</span>

export function ProspectMatchForm({capabilities,owner,saving,onOwnerChange,onSubmit}:Props){
  const [contacts,setContacts]=useState<ContactInput[]>([emptyContact()])
  function updateContact(index:number,field:keyof ContactInput,value:string){setContacts(current=>current.map((contact,i)=>i===index?{...contact,[field]:value}:contact))}
  function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);const value=(name:string)=>String(data.get(name)??'').trim();onSubmit({accountName:value('accountName'),industry:value('industry'),location:value('location'),website:value('website')||null,capabilityId:value('capabilityId'),source:value('source')||null,observedOn:value('observedOn')||null,observedFact:value('observedFact')||null,assumption:value('assumption')||null,owner:owner.trim()||null,hypothesis:value('hypothesis')||null,nextAction:value('nextAction')||null,nextActionDate:value('nextActionDate')||null,contacts:contacts.filter(contact=>Object.values(contact).some(Boolean)).map(contact=>({name:contact.name.trim(),email:contact.email.trim(),role:contact.role.trim(),notes:contact.notes.trim()}))})}
  return <form onSubmit={submit}>
    <fieldset><legend>1. Prospective account</legend><label>Account name {required}<input name="accountName" required defaultValue="Northstar Assembly Systems" /></label><label>Industry {required}<input name="industry" required defaultValue="Industrial equipment" /></label><label>Location {required}<input name="location" required defaultValue="Pune, India" /></label><label>Website <span>optional</span><input name="website" type="url" pattern="https?://.+" placeholder="https://example.com" title="Enter a complete HTTP or HTTPS URL" /></label></fieldset>
    <fieldset><legend>2. Account contacts</legend><p className="field-help wide">Add the people associated with this account. Name and email are required for each contact added.</p>{contacts.map((contact,index)=><div className="contact" key={index}><div className="contact-heading"><strong>Contact {index+1}</strong>{contacts.length>1&&<button className="text-button" type="button" onClick={()=>setContacts(current=>current.filter((_,i)=>i!==index))}>Remove</button>}</div><label>Name {required}<input required value={contact.name} onChange={event=>updateContact(index,'name',event.target.value)} /></label><label>Email {required}<input required type="email" value={contact.email} onChange={event=>updateContact(index,'email',event.target.value)} /></label><label>Role <span>optional</span><input value={contact.role} onChange={event=>updateContact(index,'role',event.target.value)} /></label><label>Notes <span>optional</span><textarea value={contact.notes} onChange={event=>updateContact(index,'notes',event.target.value)} /></label></div>)}<button className="secondary" type="button" onClick={()=>setContacts(current=>[...current,emptyContact()])}>+ Add another contact</button></fieldset>
    <fieldset><legend>3. Observed signal</legend><label>Source {required}<input name="source" placeholder="Trade publication, call, site visit…" /></label><label>Observation date {required}<input name="observedOn" type="date" /></label><label className="wide">Observed fact {required}<textarea name="observedFact" placeholder="What verifiably happened?" /></label><label className="wide">Assumption <span>optional</span><textarea name="assumption" placeholder="What are you inferring and still need to validate?" /></label></fieldset>
    <fieldset><legend>4. Capability and next action</legend><label className="wide">Capability {required}<select name="capabilityId" required defaultValue=""><option value="" disabled>Select a capability</option>{capabilities.map(item=><option key={item.id} value={item.id}>{item.name}{item.active?'':' (inactive)'}</option>)}</select></label><label className="wide">Match hypothesis {required}<textarea name="hypothesis" /></label><label>Owner {required}<input name="owner" value={owner} onChange={event=>onOwnerChange(event.target.value)} /></label><label>Next-action date {required}<input name="nextActionDate" type="date" /></label><label className="wide">Next action {required}<input name="nextAction" /></label></fieldset>
    <p className="required-note"><span className="required">*</span> Required for an active match. Missing match details can still be saved as a draft.</p><button className="primary" disabled={saving} type="submit">{saving?'Saving…':'Save capability match'}</button>
  </form>
}
