package com.brandempiricism.etocrm.platform.tenancy;
import java.net.URI;import java.time.Instant;import java.util.*;import java.util.regex.Pattern;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.security.access.prepost.PreAuthorize;
@Service class TenantProvisioningService{
 private static final Pattern SLUG=Pattern.compile("[a-z0-9]+(?:-[a-z0-9]+)*");private final TenantRegistryRepository tenants;
 TenantProvisioningService(TenantRegistryRepository tenants){this.tenants=tenants;}
 @Transactional("platformTransactionManager") @PreAuthorize("hasAuthority('platform:operate') and #actor == authentication.name") TenantView register(RegisterTenant request,String actor){String key=required(request.idempotencyKey(),"Idempotency key is required.");var existing=tenants.findByIdempotencyKey(key);if(existing.isPresent()){log(com.brandempiricism.etocrm.commons.DiagnosticEvents.Event.PROVISIONING_REPLAYED,existing.get().id,actor);return view(existing.get());}String slug=slug(request.slug());var now=Instant.now();var tenant=new TenantRegistryEntity(UUID.randomUUID(),slug,required(request.displayName(),"Client name is required."),website(request.website()),databaseName(slug),key,now,actor);tenants.save(tenant);log(com.brandempiricism.etocrm.commons.DiagnosticEvents.Event.PROVISIONING_REGISTERED,tenant.id,actor);return view(tenant);}
 @PreAuthorize("hasAuthority('platform:operate')") List<TenantView> list(){return tenants.findAllByOrderByDisplayNameAsc().stream().map(TenantProvisioningService::view).toList();}@PreAuthorize("hasAuthority('platform:operate')") TenantView get(UUID id){return view(tenants.findById(id).orElseThrow(()->new IllegalArgumentException("Client tenant does not exist.")));}
 private static void log(com.brandempiricism.etocrm.commons.DiagnosticEvents.Event event,UUID tenant,String actor){try(var context=com.brandempiricism.etocrm.commons.DiagnosticContext.forTenant(tenant,actor)){com.brandempiricism.etocrm.commons.DiagnosticEvents.afterCommit(event,tenant);}}
 static TenantView view(TenantRegistryEntity t){return new TenantView(t.id,t.slug,t.displayName,t.website,t.databaseName,t.status.name(),t.provisioningStep.name(),t.failureCode,t.createdAt,t.updatedAt);}
 private static String required(String value,String message){if(value==null||value.isBlank())throw new IllegalArgumentException(message);return value.trim();}private static String slug(String value){var result=required(value,"Client slug is required.");if(!SLUG.matcher(result).matches())throw new IllegalArgumentException("Client slug must contain lowercase letters, numbers, and single hyphens.");return result;}private static String databaseName(String slug){var value="eto_crm_"+slug.replace('-','_');if(value.length()>63)throw new IllegalArgumentException("Client slug is too long for database provisioning.");return value;}private static String website(String value){if(value==null||value.isBlank())return null;try{var uri=URI.create(value.trim());if(("http".equals(uri.getScheme())||"https".equals(uri.getScheme()))&&uri.getHost()!=null)return value.trim();}catch(IllegalArgumentException ignored){}throw new IllegalArgumentException("Client website must be a complete HTTP or HTTPS URL.");}
 record RegisterTenant(String slug,String displayName,String website,String idempotencyKey){}record TenantView(UUID id,String slug,String displayName,String website,String databaseName,String status,String provisioningStep,String failureCode,Instant createdAt,Instant updatedAt){}
}
