package com.brandempiricism.etocrm.activities.nextaction;
import com.brandempiricism.etocrm.accounts.AccountApplicationApi;import com.brandempiricism.etocrm.prospecting.ProspectingApplicationApi;import java.time.*;import java.util.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.security.access.prepost.PreAuthorize;
@Service class NextActionService{
 private final NextActionRepository actions;private final AccountApplicationApi accounts;private final ProspectingApplicationApi prospecting;
 NextActionService(NextActionRepository actions,AccountApplicationApi accounts,ProspectingApplicationApi prospecting){this.actions=actions;this.accounts=accounts;this.prospecting=prospecting;}
 @PreAuthorize("hasAuthority('crm:write')") NextActionView create(UUID accountId,CreateAction request,String actor){accounts.getAccount(accountId);var match=prospecting.getMatch(request.capabilityMatchId());if(!match.accountId().equals(accountId))throw new IllegalArgumentException("Capability match does not belong to this account.");var now=Instant.now();return view(actions.save(new NextActionEntity(UUID.randomUUID(),accountId,match.id(),required(request.description()),required(request.dueAt()),now,actor)));}
 NextActionGroups grouped(UUID accountId){accounts.getAccount(accountId);var overdue=new ArrayList<NextActionView>();var today=new ArrayList<NextActionView>();var upcoming=new ArrayList<NextActionView>();var completed=new ArrayList<NextActionView>();var current=LocalDate.now(ZoneOffset.UTC);for(var action:actions.findByAccountIdOrderByDueAtAsc(accountId)){var view=view(action);if(action.status==ActionStatus.COMPLETED)completed.add(view);else{var due=action.dueAt.atZone(ZoneOffset.UTC).toLocalDate();if(due.isBefore(current))overdue.add(view);else if(due.equals(current))today.add(view);else upcoming.add(view);}}return new NextActionGroups(overdue,today,upcoming,completed);}
 @Transactional @PreAuthorize("hasAuthority('crm:write')") NextActionView complete(UUID accountId,UUID id,String actor){var action=find(accountId,id);if(action.status!=ActionStatus.COMPLETED){var now=Instant.now();action.status=ActionStatus.COMPLETED;action.completedAt=now;action.updatedAt=now;action.updatedBy=actor;}return view(action);}
 @Transactional @PreAuthorize("hasAuthority('crm:write')") NextActionView reschedule(UUID accountId,UUID id,RescheduleAction request,String actor){var action=find(accountId,id);action.dueAt=required(request.dueAt());action.updatedAt=Instant.now();action.updatedBy=actor;return view(action);}
 private NextActionEntity find(UUID accountId,UUID id){var result=actions.findById(id).orElseThrow(()->new IllegalArgumentException("Next action does not exist."));if(!result.accountId.equals(accountId))throw new IllegalArgumentException("Next action does not belong to this account.");return result;}
 private static String required(String value){if(value==null||value.isBlank())throw new IllegalArgumentException("Next-action description is required.");return value.trim();}private static Instant required(Instant value){if(value==null)throw new IllegalArgumentException("Next-action due time is required.");return value;}
 private static NextActionView view(NextActionEntity a){return new NextActionView(a.id,a.accountId,a.capabilityMatchId,a.description,a.dueAt,a.status.name(),a.completedAt,a.createdAt,a.updatedAt);}
 record CreateAction(UUID capabilityMatchId,String description,Instant dueAt){}record RescheduleAction(Instant dueAt){}record NextActionView(UUID id,UUID accountId,UUID capabilityMatchId,String description,Instant dueAt,String status,Instant completedAt,Instant createdAt,Instant updatedAt){}record NextActionGroups(List<NextActionView> overdue,List<NextActionView> dueToday,List<NextActionView> upcoming,List<NextActionView> completed){}
}
